// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC70l48lsG6bIZW_CjDUijv_4-SpdQjhbI',
    appId: '1:43433420956:web:3b094e006a939b5cf32559',
    messagingSenderId: '43433420956',
    projectId: 'meal-app-399b2',
    authDomain: 'meal-app-399b2.firebaseapp.com',
    storageBucket: 'meal-app-399b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwhuBzQ_34WMuYuXF3W9UF-YIwPfZDRUs',
    appId: '1:43433420956:android:eec59ed33be27bcff32559',
    messagingSenderId: '43433420956',
    projectId: 'meal-app-399b2',
    storageBucket: 'meal-app-399b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFIR1uzrdk8s-6Ircek7qKAAX5bF-E-U',
    appId: '1:43433420956:ios:b6eb247c9cc09061f32559',
    messagingSenderId: '43433420956',
    projectId: 'meal-app-399b2',
    storageBucket: 'meal-app-399b2.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFIR1uzrdk8s-6Ircek7qKAAX5bF-E-U',
    appId: '1:43433420956:ios:b6eb247c9cc09061f32559',
    messagingSenderId: '43433420956',
    projectId: 'meal-app-399b2',
    storageBucket: 'meal-app-399b2.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC70l48lsG6bIZW_CjDUijv_4-SpdQjhbI',
    appId: '1:43433420956:web:a42cef2af79dcc85f32559',
    messagingSenderId: '43433420956',
    projectId: 'meal-app-399b2',
    authDomain: 'meal-app-399b2.firebaseapp.com',
    storageBucket: 'meal-app-399b2.firebasestorage.app',
  );
}
